### ISSUE TITLE
Update and make more attractive to readme.md

### ISSUE THREAD

**Issue by ayush-pandey047** [AkhzarFarhan/HactoberFest-2024#200]
The readme.me should be more attractive and there would be some emoji and easy for user to read and understand.

**Comment by Ajay-2022-Soft-Tech** [comment]
@AkhzarFarhan Working On it

**Comment by AkhzarFarhan** [comment]
Thank you for your valuable contribution @Ajay-2022-Soft-Tech

**Comment by Ajay-2022-Soft-Tech** [comment]
Please labeled as Hacktober fest
