### ISSUE TITLE
Files are in random places

### ISSUE THREAD

**Issue by AkhzarFarhan** [AkhzarFarhan/HactoberFest-2024#225]
Source code files are in random places, please help moving them to their proper folders.

**Comment by Sakshi-kumari19** [comment]
The files have been placed to the correct folder .Please consider pull request #238 to implement the changes

**Comment by Smriti-Prajapati** [comment]
Hey, please assign this issue to me.

**Comment by Sayan-dev731** [comment]
moved some of the files in the repository please check it .
