### ISSUE TITLE
Add graphs Cheat Sheet in C++ with info and basic questions.

### ISSUE THREAD

**Issue by Mayur-nimkande-20** [AkhzarFarhan/HactoberFest-2024#252]
Hello, @AkhzarFarhan i wanted to contribute to the repo by adding graph cheatsheet in c++. Do assign me this task under #hacktoberfest2024. Given below is sample image.
Thank you,
Mayur.

![image](https://github.com/user-attachments/assets/2d93563c-3979-41cb-8099-926ddb552560)

**Comment by shrutibharat-05** [comment]
I would also like to work on this repo
