### ISSUE TITLE
Add Moore's voting algorithm in java

### ISSUE THREAD

**Issue by Vishrut99** [AkhzarFarhan/HactoberFest-2024#255]
It's one of the most important algorithm in data structures and i want to add that i your repo.

**Comment by AvinashUmrao** [comment]
Moore's Voting Algorithm is used to find the majority element (an element that appears more than half the time) in an array with linear time complexity and constant space complexity. 

kindly assign this task .. would be happy to contribute @AkhzarFarhan

**Comment by priyansh2313** [comment]
i would like to get assigned to it

**Comment by AkhzarFarhan** [comment]
> Moore's Voting Algorithm is used to find the majority element (an element that appears more than half the time) in an array with linear time complexity and constant space complexity. 
> 
> kindly assign this task .. would be happy to contribute @AkhzarFarhan

Assigned, happy coding @AvinashUmrao

**Comment by AkhzarFarhan** [comment]
> i would like to get assigned to it
Assigned, happy coding @priyansh2313
